export const path = {
  homePage: "/",
  pageNotFound: "*",
  signUp: "/sign-up",
  signIn: "/sign-in",
  verify: "/verify-otp",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  services: "/services",
  serviceDetail: "/service-detail/:serviceId",
  blog: "/blog",
  blogDetail: "/blog/:blogSlug",
  ourStaff: "/our-staff",
  features: "/features",
  contacts: "/contacts",
  doctorDetail: "/doctor/:id",
  appointment: "/appointment",
  admin: "/admin",
  resendOtp: "/resend-otp",
};
